<template>
  <q-dialog>
    <q-card class="q-px-lg q-py-xl">
      <PreskoForm
        title="Presko Form"
        :fields="sessionFields"
        submit-component="AppSubmit"
        @input="handleFormInput"
        @submit="submitSession"
        @submit:reject="alertFormValidationFail"
      />
    </q-card>
  </q-dialog>
</template>

<script setup>
import PreskoForm from "presko-form";

function alertFormValidationFail() {
  alert("validation failed");
}

function handleFormInput(e) {
  console.log(e);
}

const sessionFields = [
  {
    propertyName: "topic",
    label: "Topic",
    component: "AppInput",
    rules: ["required"],
    value: "",
  },
  {
    propertyName: "description",
    label: "Description",
    component: "AppTextarea", // Assuming you've created a wrapper around q-textarea
    rules: [],
    value: "",
  },
  {
    propertyName: "url",
    label: "Session URL",
    component: "AppInput",
    rules: ["required"], // You might not need the required rule here since it's autogenerated
    // value: uuidv4(), // Assuming you've imported the uuid function
    value: Date.now(), // Assuming you've imported the uuid function
  },
  {
    propertyName: "adminUrl",
    label: "Admin URL",
    component: "AppInput",
    rules: ["required"],
    // value: uuidv4(),
    value: Date.now(),
  },
  {
    propertyName: "minutesPerRound",
    label: "Minutes per Round",
    component: "AppSlider", // A custom slider component you'd create
    rules: ["required"],
    value: 5, // Default value
  },
  {
    propertyName: "timeBetweenRounds",
    label: "Time Between Rounds",
    component: "AppSlider",
    rules: ["required"],
    value: 2, // Default value
  },
  {
    propertyName: "startingTime",
    label: "Starting Time",
    component: "AppDateTimePicker", // A custom date-time picker component
    rules: ["required"],
    value: new Date(), // Default to the current date and time
  },
];

function submitSession(e) {
  alert(e);
}
</script>
